global:
  resolve_timeout: 5m
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_match:
    severity: critical
  target_match_re:
    severity: warning|info
- equal:
  - namespace
  - alertname
  source_match:
    severity: warning
  target_match_re:
    severity: info
receivers:
- name: Default
- name: Watchdog
  webhook_configs:
  - url: 'http://discord:9094'
- name: Critical
  email_configs:
  - to: felipe.espinoza.r@uchile.cl
    from: no-reply@eol.uchile.cl
    smarthost: mtaprod.uchile.cl:25
    require_tls: false
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: Watchdog
  - match:
      severity: critical
    receiver: Critical
